version: '3.8'

services:
  db-usuario:
    image: postgres:latest
    container_name: db-usuario
    environment:
      POSTGRES_USER: dbusuario
      POSTGRES_PASSWORD: passusuario
      POSTGRES_DB: db-usuario
    ports:
      - "5432:5432"
    volumes:
      - usuario-data:/var/lib/postgresql/data

  db-item:
    image: postgres:latest
    container_name: db-item
    environment:
      POSTGRES_USER: dbitem
      POSTGRES_PASSWORD: passitem
      POSTGRES_DB: db-item
    ports:
      - "5433:5432"
    volumes:
      - item-data:/var/lib/postgresql/data

  db-pagamento:
    image: postgres:latest
    container_name: db-pagamento
    environment:
      POSTGRES_USER: dbpagamento
      POSTGRES_PASSWORD: passpagamento
      POSTGRES_DB: db-pagamento
    ports:
      - "5434:5432"
    volumes:
      - pagamento-data:/var/lib/postgresql/data

  db-carrinho:
    image: postgres:latest
    container_name: db-carrinho
    environment:
      POSTGRES_USER: dbcarrinho
      POSTGRES_PASSWORD: passcarrinho
      POSTGRES_DB: db-carrinho
    ports:
      - "5435:5432"
    volumes:
      - carrinho-data:/var/lib/postgresql/data

  ms-usuario:
    container_name: ms-usuario
    build: ../ms-usuario/.
    ports:
      - "8081:8080"
    depends_on:
      - db-usuario
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-usuario:5432/db-usuario
      SPRING_DATASOURCE_USERNAME: dbusuario
      SPRING_DATASOURCE_PASSWORD: passusuario
      PORT: 8080
      JWT_SECRET: pZ8Pst0rRsG0ylUsTSYTm97rD3P3LY3sJsIHXvG2ug4hCR15idue66UDXuq3dhBI

  ms-item:
    container_name: ms-item
    build: ../ms-item/.
    ports:
      - "8082:8080"
    depends_on:
      - db-item
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-item:5432/db-item
      SPRING_DATASOURCE_USERNAME: dbitem
      SPRING_DATASOURCE_PASSWORD: passitem
      PORT: 8080
      JWT_SECRET: pZ8Pst0rRsG0ylUsTSYTm97rD3P3LY3sJsIHXvG2ug4hCR15idue66UDXuq3dhBI
  
  ms-pagamento:
    container_name: ms-pagamento
    build: ../ms-pagamento/.
    ports:
      - "8083:8080"
    depends_on:
      - db-pagamento
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-pagamento:5432/db-pagamento
      SPRING_DATASOURCE_USERNAME: dbpagamento
      SPRING_DATASOURCE_PASSWORD: passpagamento
      PORT: 8080
      JWT_SECRET: pZ8Pst0rRsG0ylUsTSYTm97rD3P3LY3sJsIHXvG2ug4hCR15idue66UDXuq3dhBI

  ms-carrinho:
    container_name: ms-carrinho
    build: ../ms-carrinho/.
    ports:
      - "8084:8080"
    depends_on:
      - db-carrinho
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-carrinho:5432/db-carrinho
      SPRING_DATASOURCE_USERNAME: dbcarrinho
      SPRING_DATASOURCE_PASSWORD: passcarrinho
      PORT: 8080
      JWT_SECRET: pZ8Pst0rRsG0ylUsTSYTm97rD3P3LY3sJsIHXvG2ug4hCR15idue66UDXuq3dhBI
      MS_PAGAMENTO_URL: http://ms-pagamento:8080/ms-pagamento/
      MS_ITEM_URL: http://ms-item:8080/ms-item/

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  usuario-data:
  item-data:
  pagamento-data:
  carrinho-data:
