INSERT INTO TB_USUARIO (EMAIL, NOME, DATA_NASCIMENTO, DATA_REGISTRO, ROLE, PASSWORD) VALUES ('joao.silva@example.com', 'João da Silva', '1990-05-15', '2024-03-18 12:00:00', 0, '$2a$10$ZQ0U5qvzuE3WogBK90mAZ.sXxzO6VKSkMqVaNxM8pBk/aRC2aS0R2');
INSERT INTO TB_USUARIO (EMAIL, NOME, DATA_NASCIMENTO, DATA_REGISTRO, ROLE, PASSWORD) VALUES ('maria.santos@example.com', 'Maria dos Santos', '1985-09-20', '2024-03-18 12:05:00', 1, '$2a$10$K8dDZlqKWBIU.H/RxmTSCelDIj3IYLmu7FB0zJ4jecjXzqWRzpxCi');
INSERT INTO TB_USUARIO (EMAIL, NOME, DATA_NASCIMENTO, DATA_REGISTRO, ROLE, PASSWORD) VALUES ('pedro.almeida@example.com', 'Pedro Almeida', '1988-03-10', '2024-03-18 12:10:00', 0, '$2a$10$xj4eoETqizZPsW0P/3m0juO4TaL1NlBEalOaAKQnuZiHJq6nl2RLq');
INSERT INTO TB_USUARIO (EMAIL, NOME, DATA_NASCIMENTO, DATA_REGISTRO, ROLE, PASSWORD) VALUES ('ana.ferreira@example.com', 'Ana Ferreira', '1992-11-25', '2024-03-18 12:15:00', 1, '$2a$10$qq5Tiv9B81QyCFNbw8LfheerPdTflHiO5ch6/H8Xlee57zl5kGEP2');
INSERT INTO TB_USUARIO (EMAIL, NOME, DATA_NASCIMENTO, DATA_REGISTRO, ROLE, PASSWORD) VALUES ('carlos.souza@example.com', 'Carlos Souza', '1980-07-03', '2024-03-18 12:20:00', 0, '$2a$10$AExKaUbw95Pmso23pm7Kz.V8fM.g2RD/rRgJtL68gSjHXeI7F56ey');

INSERT INTO TB_ENDERECO (ID, USUARIO_EMAIL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, REFERENCIA ) VALUES (NEXTVAL ('endereco_sequence'), 'joao.silva@example.com', 'Rua das Flores', '123', 'Apto 101', 'Centro', 30140010, 'Belo Horizonte', 'MG', 'Próximo à Praça Central');
INSERT INTO TB_ENDERECO (ID, USUARIO_EMAIL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, REFERENCIA ) VALUES (NEXTVAL ('endereco_sequence'), 'joao.silva@example.com', 'Avenida Brasil', '456', 'Casa 2', 'Jardim América', 01430000, 'São Paulo', 'SP', 'Perto do Parque Ibirapuera');
INSERT INTO TB_ENDERECO (ID, USUARIO_EMAIL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, REFERENCIA ) VALUES (NEXTVAL ('endereco_sequence'), 'maria.santos@example.com', 'Avenida do Sol', '333', 'Casa 5', 'Jardim das Flores', 58011000, 'João Pessoa', 'PB', 'Próximo ao Parque Solon de Lucena');
INSERT INTO TB_ENDERECO (ID, USUARIO_EMAIL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, REFERENCIA ) VALUES (NEXTVAL ('endereco_sequence'), 'pedro.almeida@example.com', 'Rua do Comércio', '789', 'Sala 3', 'Centro', 20040008, 'Rio de Janeiro', 'RJ', 'Ao lado da Estação de Metrô');
INSERT INTO TB_ENDERECO (ID, USUARIO_EMAIL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, REFERENCIA ) VALUES (NEXTVAL ('endereco_sequence'), 'pedro.almeida@example.com', 'Rua das Palmeiras', '246', 'Apto 202', 'Jardim Botânico', 40170115, 'Salvador', 'BA', 'Próximo à Praia de Ondina');
INSERT INTO TB_ENDERECO (ID, USUARIO_EMAIL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, REFERENCIA ) VALUES (NEXTVAL ('endereco_sequence'), 'ana.ferreira@example.com', 'Rua das Margaridas', '999', 'Apto 303', 'Centro', 70002900, 'Brasília', 'DF', 'Próximo ao Congresso Nacional');
INSERT INTO TB_ENDERECO (ID, USUARIO_EMAIL, LOGRADOURO, NUMERO, COMPLEMENTO, BAIRRO, CEP, CIDADE, ESTADO, REFERENCIA ) VALUES (NEXTVAL ('endereco_sequence'), 'carlos.souza@example.com', 'Avenida Paulista', '555', 'Conjunto 1010', 'Bela Vista', 01310100, 'São Paulo', 'SP', 'Próximo ao MASP');
