INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Tênis All Stars Branco', 'All Stars', 'Calçados', 300, 299.99, '2019-03-07');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Smartphone Galaxy S21', 'Samsung' , 'Telefones e Tablets', 50, 2350.99, '2022-06-11');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Notebook Inspiron 15', 'Dell','Computadores', 30, 4999.99, '2021-03-07');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Smart TV LED 55', 'LG', 'TVs e Audio', 20, 3648, '2019-06-07');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Fone de Ouvido Bluetooth AirPods', 'Apple', 'Acessórios de Audio', 40, 1350.75, '2020-03-07');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Camera Digital EOS Rebel T7', 'Canon', 'Cameras e Filmadoras', 15, 899, '2018-09-01');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Smartwatch Versa 3', 'FITBIT', 'Wearables', 25, 568, '2017-07-03');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Console de Video Game PlayStation 5', 'Sony', 'Video Games', 10, 3999.99, '2015-05-05');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Impressora Multifuncional DeskJet', 'HP', 'Impressoras', 35, 2899.69, '2013-03-07');
INSERT INTO TB_ITEM (ID, DESCRICAO, MARCA, CATEGORIA, QUANTIDADE, VALOR_UNITARIO, DATA_ATUALIZACAO) VALUES ( NEXTVAL ('item_sequence'), 'Mochila Executiva Swissgear', 'Swissgear', 'Bolsas e Mochilas', 45, 450, '2011-01-09');










